version: "3"

services:
  web:
    container_name: carwings
    image: nginx:latest
    restart: always
    ports:
      - "8008:80/tcp"
    volumes:
      - ./html:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.3-fpm
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

